AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-doc-pipeline

  Sample SAM Template for cloud-doc-pipeline

Globals:
  Function:
    Timeout: 3

Parameters:
  ProjectName:
    Type: String
    Default: cloud-doc-pipeline
    Description: Base name used for resource naming
  StageName:
    Type: String
    Default: dev2
    AllowedValues:
      - dev2
      - prod
    Description: Deployment stage (affects naming and behavior)

Resources:
  DocumentApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
      Environment:
        Variables:
          DOCUMENTS_TABLE_NAME: !Ref DocumentsTable
          DOCUMENTS_BUCKET_NAME: !Ref DocumentsBucket
      Events:
        CreateDocument:
          Type: Api
          Properties:
            Path: /documents
            Method: post

  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-${StageName}-documents-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldNoncurrentVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30

  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${StageName}-documents"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  S3IngestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: s3_ingest.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${ProjectName}-${StageName}-documents-${AWS::AccountId}/*"
      Environment:
        Variables:
          DOCUMENTS_TABLE_NAME: !Ref DocumentsTable
      Events:
        S3UploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref DocumentsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: documents/
                  - Name: suffix
                    Value: .pdf

  ProcessDocumentDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-${StageName}-process-document-dlq"
      MessageRetentionPeriod: 1209600 # 14 days

  ProcessDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/
      Handler: process_document.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 15
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - DynamoDBStreamReadPolicy:
            TableName: !Ref DocumentsTable
            StreamName: !GetAtt DocumentsTable.StreamArn
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - !Sub "arn:aws:s3:::${ProjectName}-${StageName}-documents-${AWS::AccountId}/*"
      Environment:
        Variables:
          DOCUMENTS_TABLE_NAME: !Ref DocumentsTable
          DOCUMENTS_BUCKET_NAME: !Ref DocumentsBucket
      Events:
        DocumentsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DocumentsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 10
            MaximumRetryAttempts: 2

  ProcessDocumentErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${StageName}-ProcessDocumentFunction-Errors"
      AlarmDescription: "Alarm if ProcessDocumentFunction reports errors"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProcessDocumentFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  ProcessDocumentDLQMessagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${StageName}-ProcessDocumentDLQ-Messages"
      AlarmDescription: "Alarm if messages appear in ProcessDocument DLQ"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ProcessDocumentDLQ.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  ApiBaseUrl:
    Description: API Gateway base URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod"
  DocumentsBucketName:
    Description: S3 bucket for uploaded documents
    Value: !Ref DocumentsBucket
  DocumentsTableName:
    Description: DynamoDB table for document metadata and audit logs
    Value: !Ref DocumentsTable
  DocumentApiFunctionArn:
    Description: Document API Lambda Function ARN
    Value: !GetAtt DocumentApiFunction.Arn
  S3IngestFunctionArn:
    Description: S3 ingest Lambda Function ARN
    Value: !GetAtt S3IngestFunction.Arn
  ProcessDocumentFunctionArn:
    Description: Downstream processing Lambda ARN
    Value: !GetAtt ProcessDocumentFunction.Arn
  ProcessDocumentDLQName:
    Description: DLQ name for ProcessDocumentFunction failures
    Value: !GetAtt ProcessDocumentDLQ.QueueName
  ProcessDocumentDLQArn:
    Description: DLQ ARN for ProcessDocumentFunction failures
    Value: !GetAtt ProcessDocumentDLQ.Arn
